##########################
## Configuración global de la aplicación RentExpress
##########################

# Configuración de la base de datos
db.url=jdbc:mysql://localhost:3306/rentexpres?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.user=root
db.password=abc123.
db.driver=com.mysql.cj.jdbc.Driver

# Configuración de envío de correo
mail.email=rentexpressw1@gmail.com
mail.password=envx hipd mtif nwqp
mail.smtp.server.name=smtp.gmail.com
mail.smtp.server.port=587

# base folder para todas las imágenes (usa \\ escapadas en Windows)
base.image.path=C:\\rentexpres\\imagen

# (opcional) límite por archivo en bytes (2 MB)
base.image.max.bytes=2097152
